spec:
  template:
    spec:
      containers:
        -
          resources:
           requests:
             cpu: "0.2"
             memory: 256Mi
           limits:
             cpu: "1.0"
             memory: 768Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: spring_profiles_active
            value: deployed   
